[package]
name = "saml-hal"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0-rc.1"
embedded-hal-async = "1.0.0-rc.1"
saml11-pac = { path = "../saml11-pac",  feature = "embassy" }
embassy-hal-internal = { git = "https://github.com/embassy-rs/embassy", branch = "main" }
